ducklake:
  target: dev
  outputs:
    dev:
      type: duckdb
      database: lakehouse
      threads: 4

      extensions:
        - ducklake
        - postgres
        - httpfs
        - parquet

      secrets:

        - type: s3
          key_id: "{{ env_var('MINIO_ACCESS_KEY') }}"
          secret: "{{ env_var('MINIO_SECRET_KEY') }}"
          endpoint: "{{ env_var('MINIO_ENDPOINT') }}"
          use_ssl: false
          url_style: path

        - type: postgres
          name: catalog_credentials
          host: "{{ env_var('POSTGRES_HOST') }}"
          port: "{{ env_var('POSTGRES_PORT') }}"
          database: "{{ env_var('POSTGRES_DB') }}"
          user: "{{ env_var('POSTGRES_USER') }}"
          password: "{{ env_var('POSTGRES_PASSWORD') }}"

        - type: ducklake
          name: lakehouse
          metadata_path: ""
          data_path: "s3://smb-mdw/lakehouse/"
          metadata_parameters:
            TYPE: postgres
            SECRET: catalog_credentials
            SCHEMA: metadata

      attach:
        - path: "ducklake:lakehouse"
          alias: lakehouse
          is_ducklake: True


